### ISSUE TITLE
Author's name not displaying properly in comments - Discussion Forum - Web

### ISSUE THREAD

**Issue by Heather-Stone** [tsheils/project_cure_issues#199]
Leonard’s response to discussion is not displaying his information correctly for his replies to the discussion topic I started on Herpes Simplex Virus. Shows as: (Medium)
	   S L
	   F

![hsv discussion](https://user-images.githubusercontent.com/35972819/35686659-cdff24ba-073a-11e8-85c0-63c61f61f770.JPG)

**Comment by tsheils** [comment]
That is the name Leonard entered for his profile.

![image](https://user-images.githubusercontent.com/6415791/35697769-2cb9f3a4-0759-11e8-9f0b-2831aa8581a2.png)

**Comment by Heather-Stone** [comment]
I actually checked that and in his website profile at least, that isn’t what he entered… unless was he not logged in as leonard.sacks@fda.hhs.gov?

**Comment by tsheils** [comment]
![image](https://user-images.githubusercontent.com/6415791/35698009-d849ada4-0759-11e8-9d0c-b18be6a69105.png)
![image](https://user-images.githubusercontent.com/6415791/35698038-f1d7c602-0759-11e8-90fb-684be4381104.png)

This is the account he is using

**Comment by Heather-Stone** [comment]
Gotcha… then this is not an actual issue
