### ISSUE TITLE
secondary email

### ISSUE THREAD

**Issue by tsheils** [tsheils/project_cure_issues#23]
What is it for? It isn't shown in django, but is on the api model. Users can log in with both, but doesn't so much else. would make signup faster

**Comment by emochaadmin** [comment]
Honestly, good question for Heather. I cannot remember now why we wanted it included. (except maybe to put in an institution email address? Like tim@jhmi.edu to prove that you worked somewhere? I might be making that up though)

**Comment by tsheils** [comment]
kill it with fire.
