### ISSUE TITLE
No response to user upon failed case/discussion post submission

### ISSUE THREAD

**Issue by southalln** [tsheils/project_cure_issues#68]
POST to https://api-dev.emochacure.com/v1/reports getting a 400 Bad Request, but I don't see anything on the web page after I click 'Submit' - its like nothing happened. The error should be reported to the user, somehow, and hopefully we can capture from the log as well.

To recreate the 400 response, POST this:
{"status":"Submitted","disease":285,"why_new_way":[{"answer":"Patient failed previous therapy"}],"use_drug":[{"answer":"To treat a disease other than the one for which the drug is approved"}],"outcome":"Unknown/Not yet determined","regimens":[{"drug":9560,"drugName":"paracetamol"},{"drug":7473,"drugName":"disulfiram"}],"site_of_infection":[],"specific_site":[],"organisms":[],"how_diagnosis":[],"resistant_drugs":[],"combo_drugs":[],"how_outcome":[{"answer":"Clinical assessment"}],"when_outcome":"After a period of follow-up","how_long_time":24,"how_long_unit":"Weeks","relapse":"Don’t Know","reminder":false,"anonymous":true}

Response was {"relapse":["\"Don’t Know\" is not a valid choice."]}

**Comment by tsheils** [comment]
This can be closed for #69 , which is a separate error, and #66, which would let the user know.
